import type { SiteConfig } from "../../schemas/site.ts";
import { escapeCell, escapeText, joinSections, link } from "./markdown.ts";
import type { Model, ModelSource } from "./model.ts";

const GENERATED_NOTE =
  "_Generated from the records in `data/`. Edit those records and run `npm run generate`; do not edit this file by hand._";

export function pageTitle(source: ModelSource): string {
  return `${source.name} to Claude: connection options and setup`;
}

function websiteUrl(site: SiteConfig, path: string): string | null {
  if (!site.url.startsWith("https://")) return null;
  return new URL(path, site.url).toString();
}

export function correctionUrl(site: SiteConfig, source: ModelSource): string | null {
  if (site.repo === null) return null;
  const url = new URL(`https://github.com/${site.repo}/issues/new`);
  url.searchParams.set("template", "correction.yml");
  url.searchParams.set("labels", "correction");
  url.searchParams.set("title", `Correction: ${source.name}`);
  url.searchParams.set("source", source.slug);
  return url.toString();
}

const COUPLER_LANDING_PREFIX = "https://www.coupler.io/claude-integrations/";

const LINKS = {
  coupler: "https://www.coupler.io/",
  claudeIntegration: "https://www.coupler.io/claude-integrations",
  aiIntegrations: "https://www.coupler.io/ai-integrations",
  claudeDirectory: "https://claude.com/connectors/coupler-io",
  claudeDocs: "https://docs.coupler.io/destinations/categories/ai/claude",
  mcpDocs: "https://docs.coupler.io/ai/mcp",
  refreshDocs: "https://docs.coupler.io/functionality/flow-settings/how-to-set-up-automatic-data-refresh",
  freeProDocs: "https://docs.coupler.io/troubleshooting/claude-connector-tools-dont-load-on-free-and-pro-plans",
};

const OTHER_AI_TOOLS: Array<[string, string]> = [
  ["ChatGPT", "https://docs.coupler.io/destinations/categories/ai/chatgpt"],
  ["Cursor", "https://docs.coupler.io/destinations/categories/ai/cursor"],
  ["Perplexity", "https://docs.coupler.io/destinations/categories/ai/perplexity"],
  ["Gemini CLI", "https://docs.coupler.io/destinations/categories/ai/gemini"],
  ["Gemini Enterprise", "https://docs.coupler.io/destinations/categories/ai/gemini_enterprise"],
  ["Microsoft Copilot Studio", "https://docs.coupler.io/destinations/categories/ai/ms_copilot_studio"],
  ["OpenClaw", "https://docs.coupler.io/destinations/categories/ai/openclaw"],
  ["Any MCP-compatible client (Custom MCP)", "https://docs.coupler.io/destinations/categories/ai/custom_mcp"],
];

function couplerLandingPage(source: ModelSource): string | null {
  return source.evidence.find((item) => item.url?.startsWith(COUPLER_LANDING_PREFIX))?.url ?? null;
}

function sampleQuery(source: ModelSource): string | null {
  return source.options.find((option) => option.provider === "Coupler.io")?.sample_query ?? null;
}

function sourceTable(model: Model, home: string | null): string {
  if (model.sources.length === 0) return "No sources have been added yet.";
  return [
    "| Source | Ask Claude, for example | Guides |",
    "| --- | --- | --- |",
    ...model.sources.map((source) => {
      const landing = couplerLandingPage(source);
      const guides = [
        home ? link("Setup guide", new URL(`/sources/${source.slug}/`, home).toString()) : null,
        landing ? link(`${source.name} to Claude on Coupler.io`, landing) : null,
      ].filter((item): item is string => item !== null);
      const query = sampleQuery(source);
      return `| ${escapeCell(source.name)} | ${query ? `“${escapeText(query)}”` : "—"} | ${guides.join(" · ") || "—"} |`;
    }),
  ].join("\n");
}

function faq(items: Array<[string, string]>): string {
  return items.map(([question, answer]) => `### ${question}\n\n${answer}`).join("\n\n");
}

export function renderReadme(model: Model): string {
  const { site } = model;
  const home = websiteUrl(site, "/");

  return joinSections([
    `# ${escapeText(site.name)}`,
    `**${escapeText(site.tagline)}**`,
    [
      `AI Data Connectors is a guide to bringing business data into Claude with ${link("Coupler.io", LINKS.coupler)}. Coupler.io imports data from more than 400 apps, such as Google Ads, Google Analytics 4, QuickBooks, and Pipedrive, keeps it fresh on a schedule, and serves it to Claude through its own MCP server. You then ask questions about your numbers in plain language, with no SQL, exports, or copy-paste.`,
      "",
      [
        link("Connect your data to Claude", LINKS.claudeIntegration),
        link("Coupler.io in the Claude connectors directory", LINKS.claudeDirectory),
        link("Setup documentation", LINKS.claudeDocs),
        home ? link("Browse the directory", home) : null,
      ]
        .filter((item): item is string => item !== null)
        .join(" · "),
    ].join("\n"),
    "## How to connect your business data to Claude",
    [
      `1. **Connect.** In Coupler.io, create a data flow: pick one or more sources, filter and shape the data, and choose Claude as the destination.`,
      `2. **Schedule.** Run the flow once, then set it to refresh automatically. Coupler.io supports intervals from every 15 minutes to monthly, depending on your plan (${link("refresh docs", LINKS.refreshDocs)}).`,
      `3. **Ask.** Add the Coupler.io connector in Claude, open a new chat, and ask, for example, “Which campaigns generated the most conversions last month?” Claude asks permission to use the Coupler.io tools the first time.`,
      `4. **Act.** Ask follow-up questions, compare periods, and turn the answers into budget, pipeline, or forecasting decisions.`,
      "",
      "The same connector works in Claude web, Claude desktop, Claude mobile, Cowork, and Claude Code.",
    ].join("\n"),
    "## Why use Coupler.io to connect data to Claude",
    [
      `- **Your source systems stay out of reach.** Claude never connects to Google Ads, QuickBooks, or your CRM directly. It queries the datasets Coupler.io has imported, and those queries are read-only.`,
      `- **Large datasets just work.** Queries run on Coupler.io's side through the ${link("Coupler.io MCP server", LINKS.mcpDocs)}, so a large dataset does not have to fit into Claude's context window.`,
      "- **Many sources, one conversation.** A single data flow can join or append several sources, for example ad spend with GA4 sessions and CRM deals, before Claude sees the data.",
      "- **You decide what Claude sees.** Claude only sees datasets from data flows that have Claude as their destination, and you can drop columns or filter rows before they leave Coupler.io.",
      "- **Verified and compliant.** The Coupler.io connector is listed in Claude's connectors directory as Anthropic verified, and Coupler.io states it is SOC 2 Type II certified and GDPR and HIPAA compliant.",
      "- **No code required.** You set everything up in Coupler.io's interface and ask your questions in plain language.",
    ].join("\n"),
    "## Data sources you can connect to Claude",
    [
      `Each source below has a researched guide that explains what data Coupler.io imports, how often it refreshes, and which limits to expect. Coupler.io supports far more apps than are listed here; see the ${link("full list of Claude integrations", LINKS.claudeIntegration)}.`,
      "",
      sourceTable(model, home),
    ].join("\n"),
    "## Use the same data in other AI tools",
    [
      `The Coupler.io MCP server also connects your data to other AI assistants and agents. Add each tool as a destination on a data flow to make its datasets available there. See ${link("Coupler.io AI integrations", LINKS.aiIntegrations)}.`,
      "",
      ...OTHER_AI_TOOLS.map(([name, url]) => `- ${link(name, url)}`),
    ].join("\n"),
    "## Frequently asked questions",
    faq([
      [
        "How do I connect my business data to Claude?",
        `Create a data flow in Coupler.io with your source and Claude as the destination, run it, and add the Coupler.io connector in Claude. The ${link("Claude destination guide", LINKS.claudeDocs)} walks through Claude web, desktop, Cowork, and Claude Code.`,
      ],
      [
        "Can Claude change the data in my apps?",
        `No. Claude reads the datasets Coupler.io has imported, and those queries are read-only. With your confirmation, Claude can change your Coupler.io workspace, for example by creating a data flow or triggering a refresh, but it cannot edit your campaigns, invoices, or deals. See ${link("what the MCP server can and cannot do", LINKS.mcpDocs)}.`,
      ],
      [
        "How fresh is the data Claude sees?",
        "As fresh as your schedule. Each run replaces the dataset, and Coupler.io supports refresh intervals from every 15 minutes to monthly, depending on your plan. Start a new chat after a run to pick up the latest data.",
      ],
      [
        "Does it work on Claude Free and Pro plans?",
        `Yes, with a caveat. On individual Free and Pro plans, the official connector can connect but fail to load its tools. The documented workaround is to add Coupler.io as a custom connector using the URL from your Coupler.io account (${link("troubleshooting guide", LINKS.freeProDocs)}). On Team and Enterprise plans, an admin adds the connector.`,
      ],
      [
        "Do I need technical skills?",
        "No. Data flows are configured in Coupler.io's interface, and you analyze the data by asking Claude questions in plain language.",
      ],
    ]),
    "---",
    "## For developers and contributors",
    "### About this repository",
    [
      "This repository holds one maintained dataset describing how to get data from a business source into Claude with Coupler.io, and generates the README, the website, and a public JSON dataset from it.",
      "",
      "It is an editorial directory, not a connector service. It does not authenticate users, access business data, or host an MCP server. Coverage is not exhaustive: a source appears once it is documented with cited evidence.",
      "",
      home ? `Website: ${link(site.name, home)}` : "The public website URL is not configured yet.",
    ].join("\n"),
    "### How claims are recorded",
    [
      "Each capability is stored as a claim with a status. A known claim cites the evidence it comes from and the date that evidence was read. Anything not documented is shown as “Unknown” rather than as a “no”.",
    ].join("\n"),
    "### Repository commands",
    [
      "| Command | Result |",
      "| --- | --- |",
      "| `npm ci` | Install the locked dependency tree. |",
      "| `npm run validate` | Validate records and references. |",
      "| `npm run generate` | Regenerate this README, site content, and public exports. |",
      "| `npm run check:generated` | Fail if committed generated files are stale. |",
      "| `npm test` | Run the schema, generation, and export tests. |",
      "| `npm run build` | Validate, generate, and build the static site and its search index. |",
      "| `npm run preview` | Serve the production build locally, including search. |",
      "| `npm run dev` | Run a development server with hot reload. |",
    ].join("\n"),
    "### Corrections",
    site.repo
      ? `Open an issue in ${link(site.repo, `https://github.com/${site.repo}/issues`)} using the correction template. Each source page links to a prefilled issue for that source.`
      : "Corrections are reported as repository issues using the correction template, and each source page links to a prefilled issue for its source.",
    `---\n\n${GENERATED_NOTE}`,
  ]);
}
