import type { Claim } from "../../schemas/common.ts";
import type { SiteConfig } from "../../schemas/site.ts";
import { buildInstall, type InstallLink, type ToolInstall } from "./install.ts";
import { escapeRichText, escapeText, formatValue, joinSections, link } from "./markdown.ts";
import { GUIDE_FILE, guideFile } from "./paths.ts";
import {
  orderFaq,
  type Model,
  type ModelAiTools,
  type ModelOption,
  type ModelSkill,
  type ModelSource,
} from "./model.ts";
import { correctionUrl, pageTitle, websiteUrl } from "./render-github.ts";
import { SKILLS_REPO_URL } from "../../site/src/lib/skills.ts";

const GENERATED_NOTE =
  "_Generated from the records in `data/`. Edit those records and run `npm run generate`; do not edit this file by hand._";

/** Unknown is always "Not documented", so a missing fact can never read as a "no". */
function claimText(claim: Claim<unknown>): string {
  const note = claim.note ? ` (${claim.note})` : "";
  if (claim.status === "known") return `${formatValue(claim.value)}${note}`;
  if (claim.status === "not_applicable") return `Not applicable${note}`;
  return `Not documented${note}`;
}

function claimList(claim: Claim<unknown>): string[] {
  if (claim.status !== "known") return [escapeText(claimText(claim))];
  const values = Array.isArray(claim.value) ? claim.value : [claim.value];
  return values.map((value) => `- ${escapeText(formatValue(value))}`);
}

/** One short value stays on the label line; several become a list, so they stay readable. */
function fact(label: string, claim: Claim<unknown>): string {
  const values = claim.status === "known" && Array.isArray(claim.value) ? claim.value : [];
  if (values.length < 2) return `**${label}.** ${escapeText(claimText(claim))}`;
  return [`**${label}**`, "", ...values.map((value) => `- ${escapeText(formatValue(value))}`)].join("\n");
}

function links(items: InstallLink[]): string {
  return items.map((item) => link(item.label, item.url)).join(" · ");
}

function bestFor(source: ModelSource, option: ModelOption): string[] {
  return source.recommendations
    .filter((recommendation) => recommendation.option_id === option.id)
    .map((recommendation) => `**Best for ${escapeText(recommendation.job)}.** ${escapeText(recommendation.reason)}`);
}

function identity(option: ModelOption, tools: ToolInstall[]): string {
  const rows = [
    `- Provider: ${escapeText(option.provider)}`,
    `- Connection method: ${escapeText(option.method_label)}`,
    `- Maintainer: ${escapeText(claimText(option.maintainer))}`,
    `- Availability: ${escapeText(claimText(option.route_status))}`,
    `- Access: ${escapeText(claimText(option.access))}`,
    `- Works with: ${tools.map((entry) => escapeText(entry.tool.name)).join(", ")}`,
  ];
  if (option.directory_listing.status === "known") {
    rows.push(`- Listed in Claude's connector directory: ${link("directory entry", option.directory_listing.value as string)}`);
  }
  return rows.join("\n");
}

function toolSection(source: ModelSource, option: ModelOption, install: ToolInstall): string {
  const lines = [`#### Connect ${escapeText(source.name)} to ${escapeText(install.tool.name)} with ${escapeText(option.name)}`];
  if (install.intro.length > 0) lines.push("", escapeText(install.intro.join(" ")));

  for (const group of install.groups) {
    lines.push("", `**${escapeText(group.title)}**`, "");
    group.steps.forEach((step, index) => lines.push(`${index + 1}. ${escapeRichText(step)}`));
  }
  if (install.success_check) {
    lines.push("", `**Check it worked.** ${escapeRichText(install.success_check)}`);
  }
  if (install.notes.length > 0) {
    lines.push("", "**Good to know**", "", ...install.notes.map((note) => `- ${escapeRichText(note)}`));
  }
  lines.push("", links(install.links));
  return lines.join("\n");
}

function optionSections(source: ModelSource, option: ModelOption, aiTools: ModelAiTools): string[] {
  const install = buildInstall(option, aiTools);
  const out: string[] = [`## ${escapeText(option.name)}`];

  const lead = [option.description ? escapeText(option.description) : null, identity(option, install.tools)]
    .filter((part): part is string => part !== null)
    .join("\n\n");
  out.push(lead);

  for (const line of bestFor(source, option)) out.push(line);

  if (option.capabilities.length > 0) {
    out.push(
      [`### What you can do with ${escapeText(option.name)}`, "", ...option.capabilities.map((item) => `- ${escapeText(item.text)}`)].join("\n"),
    );
  }

  out.push(
    [`### What ${escapeText(option.name)} gives you from ${escapeText(source.name)}`, "", ...claimList(option.data_available)].join("\n"),
  );

  out.push(
    [
      "### How the data reaches the AI tool",
      "",
      escapeText(claimText(option.data_path)),
      "",
      fact("Historical data", option.history),
      "",
      fact("Refresh", option.refresh),
      "",
      fact("Combining several sources", option.multi_source),
      "",
      fact("Prerequisites", option.prerequisites),
    ].join("\n"),
  );

  out.push([`### Limits to expect`, "", ...claimList(option.limits)].join("\n"));

  if (option.sample_query) {
    out.push(["### An example question you can ask", "", `> ${escapeText(option.sample_query)}`].join("\n"));
  }

  const howTo = [`### How to install ${escapeText(option.name)}`, "", "Follow the steps for the AI tool you use."];
  if (aiTools.shared_notes.length > 0) {
    howTo.push("", ...aiTools.shared_notes.map((note) => `- ${escapeText(note.text)}`));
  }
  out.push(howTo.join("\n"));

  for (const tool of install.tools) out.push(toolSection(source, option, tool));

  const tail: string[] = [];
  if (install.setup_time) {
    tail.push(`**Setup time.** ${escapeText(install.setup_time.range)}. ${escapeText(install.setup_time.basis)}`);
  }
  if (install.links.length > 0) tail.push(`More from the provider: ${links(install.links)}`);
  if (tail.length > 0) out.push(tail.join("\n\n"));

  return out;
}

/**
 * Upstream summaries are trigger text stuffed with the example questions, so the questions are
 * shown on their own where they exist and the summary is the fallback, as on the website.
 */
function skillEntry(skill: ModelSkill): string {
  const body =
    skill.questions.length > 0
      ? `for questions like ${skill.questions.map((question) => `"${escapeText(question)}"`).join(", ")}.`
      : escapeText(skill.summary);
  const needs =
    skill.also_needs.length > 0 ? ` Also needs ${skill.also_needs.map(escapeText).join(", ")}.` : "";
  return `- ${link(skill.title, skill.url)}: ${body}${needs}`;
}

function skillsSection(source: ModelSource, snapshot: Model["skills_snapshot"]): string {
  const recorded = source.related_skills.map(
    (skill) =>
      `- ${link(skill.name, skill.url)}: ${escapeText(skill.description)}` +
      (skill.also_needs.length > 0 ? ` Also needs ${skill.also_needs.map(escapeText).join(", ")}.` : ""),
  );
  const matched = source.skills.map(skillEntry);
  const entries = [...recorded, ...matched];

  const lines = ["## Related skills", ""];
  if (entries.length === 0) {
    lines.push(
      `No source-specific skill is listed yet. Browse the ${link("coupler-io/skills", SKILLS_REPO_URL)} repository.`,
    );
    return lines.join("\n");
  }
  lines.push(
    `A skill gives the AI tool instructions for a task. It connects no data, so connect ${escapeText(source.name)} first.`,
    "",
    ...entries,
  );
  if (snapshot) {
    lines.push(
      "",
      `Skills list taken from ${link(snapshot.repo, `https://github.com/${snapshot.repo}`)} at commit \`${snapshot.commit_sha.slice(0, 7)}\`.`,
    );
  }
  return lines.join("\n");
}

function faqSection(source: ModelSource): string | null {
  if (source.faq.length === 0) return null;
  const lines = ["## Questions"];
  for (const entry of orderFaq(source.faq)) {
    lines.push("", `### ${escapeText(entry.question)}`, "", escapeText(entry.answer));
  }
  return lines.join("\n");
}

function sourcesSection(source: ModelSource, site: SiteConfig): string {
  const lines = [
    "## Sources and corrections",
    "",
    `Researched on ${source.research.searched_on}. ${escapeText(source.research.coverage_note)}`,
    "",
    "Every claim above was read from one of these pages on the date shown.",
    "",
  ];
  for (const item of source.evidence) {
    if (!item.url) continue;
    lines.push(`- ${link(item.title, item.url)} — ${escapeText(item.publisher)}, read ${item.checked_on}`);
  }

  const correction = correctionUrl(site, source);
  if (correction) {
    lines.push("", `Something here wrong or out of date? ${link("Open a correction issue", correction)}.`);
  }
  return lines.join("\n");
}

function relatedSection(source: ModelSource): string | null {
  if (source.related.length === 0) return null;
  return [
    "## Related connectors",
    "",
    ...source.related.map((related) => `- ${link(related.name, `../${related.slug}/${GUIDE_FILE}`)}`),
  ].join("\n");
}

export function guidePath(site: SiteConfig, slug: string): string {
  return site.repo
    ? `https://raw.githubusercontent.com/${site.repo}/main/${guideFile(slug)}`
    : guideFile(slug);
}

function affiliation(site: SiteConfig): string {
  const who = site.maintainer.relationship_confirmed
    ? `${site.maintainer.name}, who works at Coupler.io`
    : site.maintainer.name;
  return (
    `Maintained by ${who}. These guides document and recommend Coupler.io, a commercial product, ` +
    "so this is not an independent comparison. Not affiliated with Anthropic, OpenAI, or Google."
  );
}

function toolNames(source: ModelSource, aiTools: ModelAiTools): string[] {
  const used = new Set(source.options.flatMap((option) => option.works_with));
  return aiTools.tools.filter((tool) => used.has(tool.id)).map((tool) => tool.name);
}

/**
 * Repository-level index of the committed guides. Separate from the site's /llms.txt, which points
 * at HTML pages; this one points at the Markdown files so a reader never needs the website.
 */
export function renderLlmsIndex(model: Model): string {
  const { site } = model;
  const lines = [
    `# ${site.name}`,
    "",
    `> ${site.tagline}`,
    "",
    affiliation(site),
    "",
    'Every capability below is recorded as a claim with the page it was read from. Anything the vendor does not document is labelled "Not documented" rather than as unsupported, and coverage is not exhaustive.',
    "",
    "Each guide is a single plain-Markdown file covering one data source: what Coupler.io imports from it, how the data reaches the AI tool, what the limits are, install steps for each AI tool, and the sources behind every claim.",
    "",
  ];

  if (model.sources.length > 0) {
    lines.push("## Guides", "");
    for (const source of model.sources) {
      const tools = toolNames(source, model.ai_tools);
      const install = tools.length > 0 ? ` Install steps for ${tools.join(", ")}.` : "";
      lines.push(`- [${pageTitle(source)}](${guidePath(site, source.slug)}): ${source.summary}${install}`);
    }
    lines.push("");
  }

  lines.push("## Optional", "");
  if (site.repo) {
    lines.push(`- [README](https://github.com/${site.repo}#readme): how Coupler.io connects any of these sources to an LLM, and the full source list.`);
  } else {
    lines.push("- [README](README.md): how Coupler.io connects any of these sources to an LLM, and the full source list.");
  }
  const home = websiteUrl(site, "/");
  if (home) lines.push(`- [Website](${home}): the same guides as HTML, with search.`);
  const dataset = websiteUrl(site, "/connectors.json");
  if (dataset) lines.push(`- [Public dataset, schema version 1](${dataset}): every claim and its evidence as JSON.`);

  return `${lines.join("\n")}\n`;
}

export function renderGuide(
  source: ModelSource,
  site: SiteConfig,
  aiTools: ModelAiTools,
  snapshot: Model["skills_snapshot"] = null,
): string {
  const page = websiteUrl(site, `/sources/${source.slug}/`);
  const aliases =
    source.aliases.length > 0 ? `Also known as ${source.aliases.map(escapeText).join(", ")}.` : null;

  return joinSections([
    `# ${escapeText(pageTitle(source))}`,
    escapeText(source.summary),
    aliases,
    ...source.options.flatMap((option) => optionSections(source, option, aiTools)),
    skillsSection(source, snapshot),
    faqSection(source),
    sourcesSection(source, site),
    relatedSection(source),
    page ? `This guide is also published at ${link(page, page)}.` : null,
    "---",
    GENERATED_NOTE,
  ]);
}
