import type { SiteConfig } from "../../schemas/site.ts";
import { SURFACES } from "../../schemas/source.ts";
import type { Claim } from "../../schemas/common.ts";
import {
  bulletList,
  escapeCell,
  escapeText,
  joinSections,
  link,
  renderClaim,
  renderClaimCell,
} from "./markdown.ts";
import { SURFACE_LABELS, type Model, type ModelOption, type ModelSource } from "./model.ts";

const GENERATED_NOTE =
  "_Generated from the records in `data/`. Edit those records and run `npm run generate`; do not edit this file by hand._";

export function guideTitle(source: ModelSource): string {
  return `${source.name} to Claude: connection options and setup`;
}

function websiteUrl(site: SiteConfig, path: string): string | null {
  if (!site.url.startsWith("https://")) return null;
  return new URL(path, site.url).toString();
}

export function correctionUrl(site: SiteConfig, source: ModelSource): string | null {
  if (site.repo === null) return null;
  const url = new URL(`https://github.com/${site.repo}/issues/new`);
  url.searchParams.set("template", "correction.yml");
  url.searchParams.set("labels", "correction");
  url.searchParams.set("title", `Correction: ${source.name}`);
  url.searchParams.set("source", source.slug);
  return url.toString();
}

function surfaceSummary(option: ModelOption): string {
  const supported = SURFACES.filter((surface) => {
    const claim = option.surfaces[surface] as Claim<string>;
    return claim.status === "known" && (claim.value === "supported" || claim.value === "limited");
  }).map((surface) => {
    const claim = option.surfaces[surface] as Claim<string>;
    return claim.value === "limited" ? `${SURFACE_LABELS[surface]} (limited)` : SURFACE_LABELS[surface];
  });
  return supported.length > 0 ? supported.join(", ") : "Unknown";
}

function optionSummaryTable(source: ModelSource): string {
  const header = [
    "| Option | Provider | Connection method | Maintainer | Claude surfaces | Availability |",
    "| --- | --- | --- | --- | --- | --- |",
  ];
  const rows = source.options.map((option) => {
    return [
      "",
      escapeCell(option.name),
      escapeCell(option.provider),
      escapeCell(option.method_label),
      escapeCell(option.maintainer_label),
      escapeCell(surfaceSummary(option)),
      renderClaimCell(option.route_status),
      "",
    ].join(" | ").trim();
  });
  return [...header, ...rows].join("\n");
}

function optionDetail(source: ModelSource, option: ModelOption, site: SiteConfig): string {
  const lines: string[] = [`### ${escapeText(option.name)}`];
  if (option.badges.length > 0) lines.push(`_${option.badges.map(escapeText).join(" · ")}_`);
  if (option.description) lines.push(escapeText(option.description));

  const rows: Array<[string, string]> = [
    ["Provider", escapeCell(option.provider)],
    ["Connection method", escapeCell(option.method_label)],
    ["Maintainer", renderClaimCell(option.maintainer)],
    ["Availability", renderClaimCell(option.route_status)],
    ...SURFACES.map(
      (surface) => [SURFACE_LABELS[surface], renderClaimCell(option.surfaces[surface] as Claim<unknown>)] as [string, string],
    ),
    ["Access", renderClaimCell(option.access)],
    ["Data available", renderClaimCell(option.data_available)],
    ["Historical data", renderClaimCell(option.history)],
    ["Refresh", renderClaimCell(option.refresh)],
    ["Cross-source analysis", renderClaimCell(option.multi_source)],
    ["Prerequisites", renderClaimCell(option.prerequisites)],
    ["Price note", renderClaimCell(option.pricing)],
    ["Data path", renderClaimCell(option.data_path)],
    ["Limits", renderClaimCell(option.limits)],
    ["Listed in Claude directory", renderClaimCell(option.directory_listing)],
  ];
  if (option.setup_time) {
    rows.push([
      "Setup time",
      escapeCell(
        option.setup_time.status === "known"
          ? `${option.setup_time.value!.min_minutes}–${option.setup_time.value!.max_minutes} minutes (${option.setup_time.value!.basis})`
          : renderClaim(option.setup_time),
      ),
    ]);
  }

  lines.push("", "| Field | Value |", "| --- | --- |");
  for (const [label, value] of rows) lines.push(`| ${label} | ${value} |`);

  const links: string[] = [];
  if (option.links.overview) links.push(link("Overview", option.links.overview));
  if (option.links.setup) links.push(link("Setup instructions", option.links.setup));
  if (option.links.pricing) links.push(link("Pricing", option.links.pricing));
  if (option.directory_listing.status === "known") {
    links.push(link("Claude directory entry", option.directory_listing.value!));
  }
  if (links.length > 0) lines.push("", `Links: ${links.join(" · ")}`);

  if (option.setup_steps.length > 0) {
    lines.push("", "**Setup**", "");
    option.setup_steps.forEach((step, index) => lines.push(`${index + 1}. ${escapeText(step.text)}`));
  }
  if (option.claude_configuration.length > 0) {
    lines.push("", "**Claude configuration**", "");
    lines.push(...bulletList(option.claude_configuration.map((step) => step.text)));
  }
  if (option.sample_query) {
    lines.push("", "**Sample question**", "", `> ${escapeText(option.sample_query)}`);
  }
  if (option.success_check) {
    lines.push("", `**Check it worked:** ${escapeText(option.success_check.text)}`);
  }

  return lines.join("\n");
}

function recommendationsSection(source: ModelSource, site: SiteConfig): string | null {
  if (source.recommendations.length === 0) return null;
  const lines = ["## Which route suits which job"];
  for (const recommendation of source.recommendations) {
    lines.push("", `### ${escapeText(recommendation.job)}`, "", `**${escapeText(recommendation.option_name)}.** ${escapeText(recommendation.reason)}`);
    const option = source.options.find((candidate) => candidate.id === recommendation.option_id);
  }
  return lines.join("\n");
}

function faqSection(source: ModelSource): string | null {
  if (source.faq.length === 0) return null;
  const lines = ["## Questions"];
  for (const entry of source.faq) {
    lines.push("", `### ${escapeText(entry.question)}`, "", escapeText(entry.answer));
  }
  return lines.join("\n");
}

function sourcesSection(source: ModelSource, site: SiteConfig): string {
  const lines = ["## Sources and corrections"];
  lines.push("", `Researched on ${source.research.searched_on}. ${escapeText(source.research.coverage_note)}`);

  if (source.evidence.length > 0) {
    lines.push("", "Evidence:", "");
    for (const item of source.evidence) {
      lines.push(`- ${link(item.title, item.url!)} — ${escapeText(item.publisher)}, checked ${item.checked_on}`);
    }
  }

  const correction = correctionUrl(site, source);
  if (correction) lines.push("", `Found something wrong? ${link("Open a correction issue", correction)}.`);
  return lines.join("\n");
}

export function renderGuide(source: ModelSource, site: SiteConfig): string {
  const canonical = websiteUrl(site, `/sources/${source.slug}/`);
  const usableRoutes = source.options.filter((option) => option.is_usable_route);

  return joinSections([
    `# ${escapeText(guideTitle(source))}`,
    canonical ? `Canonical version: ${link(`${site.name} — ${source.name}`, canonical)}` : null,
    `_${escapeText(site.affiliation_statement)}_`,
    escapeText(source.summary),
    usableRoutes.length > 0
      ? `**Covered in this guide:** ${usableRoutes.map((option) => escapeText(option.name)).join(", ")}.`
      : null,
    "## Compare the options",
    optionSummaryTable(source),
    "## Option details",
    ...source.options.map((option) => optionDetail(source, option, site)),
    recommendationsSection(source, site),
    faqSection(source),
    sourcesSection(source, site),
    source.related.length > 0
      ? `## Related sources\n\n${source.related
          .map((related) => `- ${link(related.name, `${related.slug}.md`)}`)
          .join("\n")}`
      : null,
    `---\n\n${GENERATED_NOTE}`,
  ]);
}

export function renderReadme(model: Model): string {
  const { site } = model;
  const home = websiteUrl(site, "/");

  const table =
    model.sources.length > 0
      ? [
          "| Source | Category | Routes | Guide |",
          "| --- | --- | --- | --- |",
          ...model.sources.map((source) =>
            [
              "",
              escapeCell(source.name),
              escapeCell(source.category_name),
              String(source.options.filter((option) => option.is_usable_route).length),
              link("Guide", `guides/${source.slug}.md`),
              "",
            ].join(" | ").trim(),
          ),
        ].join("\n")
      : "No source guides have been added yet.";

  return joinSections([
    `# ${escapeText(site.name)}`,
    escapeText(site.tagline),
    `_${escapeText(site.affiliation_statement)}_`,
    home ? `Website: ${link(site.name, home)}` : "The public website URL is not configured yet.",
    "## What this is",
    [
      "This repository holds one maintained dataset describing ways to get data from a business source into Claude, and generates the website, these Markdown guides, and a public JSON dataset from it.",
      "",
      "It is an editorial directory, not a connector service. It does not authenticate users, access business data, or host an MCP server. Coverage is not exhaustive: a route appears once it is documented with cited evidence.",
    ].join("\n"),
    "## Sources",
    table,
    "## How claims are recorded",
    [
      "Each capability is stored as a claim with a status. A known claim cites the evidence it comes from and the date that evidence was read. Anything not documented is shown as “Unknown” rather than as a “no”.",
    ].join("\n"),
    "## Repository commands",
    [
      "| Command | Result |",
      "| --- | --- |",
      "| `npm ci` | Install the locked dependency tree. |",
      "| `npm run validate` | Validate records and references. |",
      "| `npm run generate` | Regenerate this README, the guides, site content, and public exports. |",
      "| `npm run check:generated` | Fail if committed generated files are stale. |",
      "| `npm test` | Run the schema, generation, export, and export tests. |",
      "| `npm run build` | Validate, generate, and build the static site and its search index. |",
      "| `npm run preview` | Serve the production build locally, including search. |",
      "| `npm run dev` | Run a development server with hot reload. |",
    ].join("\n"),
    "## Corrections",
    site.repo
      ? `Open an issue in ${link(site.repo, `https://github.com/${site.repo}/issues`)} using the correction template. Each guide links to a prefilled issue for that source.`
      : "Corrections are reported as repository issues using the correction template, and each guide links to a prefilled issue for its source.",
    `---\n\n${GENERATED_NOTE}`,
  ]);
}
