import type { SiteConfig } from "../../schemas/site.ts";
import { escapeCell, escapeText, joinSections, link } from "./markdown.ts";
import type { Model, ModelSource } from "./model.ts";

const GENERATED_NOTE =
  "_Generated from the records in `data/`. Edit those records and run `npm run generate`; do not edit this file by hand._";

export function pageTitle(source: ModelSource): string {
  return `${source.name} to Claude: connection options and setup`;
}

function websiteUrl(site: SiteConfig, path: string): string | null {
  if (!site.url.startsWith("https://")) return null;
  return new URL(path, site.url).toString();
}

export function correctionUrl(site: SiteConfig, source: ModelSource): string | null {
  if (site.repo === null) return null;
  const url = new URL(`https://github.com/${site.repo}/issues/new`);
  url.searchParams.set("template", "correction.yml");
  url.searchParams.set("labels", "correction");
  url.searchParams.set("title", `Correction: ${source.name}`);
  url.searchParams.set("source", source.slug);
  return url.toString();
}

export function renderReadme(model: Model): string {
  const { site } = model;
  const home = websiteUrl(site, "/");

  const table =
    model.sources.length > 0
      ? [
          "| Source | Routes | Page |",
          "| --- | --- | --- |",
          ...model.sources.map((source) =>
            [
              "",
              escapeCell(source.name),
              String(source.options.filter((option) => option.is_usable_route).length),
              home ? link("Page", new URL(`/sources/${source.slug}/`, home).toString()) : "—",
              "",
            ].join(" | ").trim(),
          ),
        ].join("\n")
      : "No sources have been added yet.";

  return joinSections([
    `# ${escapeText(site.name)}`,
    escapeText(site.tagline),
    `_${escapeText(site.affiliation_statement)}_`,
    home ? `Website: ${link(site.name, home)}` : "The public website URL is not configured yet.",
    "## What this is",
    [
      "This repository holds one maintained dataset describing ways to get data from a business source into AI assistants and agents, and generates the website and a public JSON dataset from it.",
      "",
      "It is an editorial directory, not a connector service. It does not authenticate users, access business data, or host an MCP server. Coverage is not exhaustive: a route appears once it is documented with cited evidence.",
    ].join("\n"),
    "## Sources",
    table,
    "## How claims are recorded",
    [
      "Each capability is stored as a claim with a status. A known claim cites the evidence it comes from and the date that evidence was read. Anything not documented is shown as “Unknown” rather than as a “no”.",
    ].join("\n"),
    "## Repository commands",
    [
      "| Command | Result |",
      "| --- | --- |",
      "| `npm ci` | Install the locked dependency tree. |",
      "| `npm run validate` | Validate records and references. |",
      "| `npm run generate` | Regenerate this README, site content, and public exports. |",
      "| `npm run check:generated` | Fail if committed generated files are stale. |",
      "| `npm test` | Run the schema, generation, and export tests. |",
      "| `npm run build` | Validate, generate, and build the static site and its search index. |",
      "| `npm run preview` | Serve the production build locally, including search. |",
      "| `npm run dev` | Run a development server with hot reload. |",
    ].join("\n"),
    "## Corrections",
    site.repo
      ? `Open an issue in ${link(site.repo, `https://github.com/${site.repo}/issues`)} using the correction template. Each source page links to a prefilled issue for that source.`
      : "Corrections are reported as repository issues using the correction template, and each source page links to a prefilled issue for its source.",
    `---\n\n${GENERATED_NOTE}`,
  ]);
}
